import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
          {/* UCAN Invest - Social Media */}
          Invest - Social Media
        </h1>

        {/* Continuacao da pagina */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.edsonduma.ga/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} UCAN
        </a>
      </footer>
    </div>
  )
}
